### ISSUE TITLE
dEploid mcmc not converging

### ISSUE THREAD

**Issue by bredelings** [DEploid-dev/DEploid#346]
**Describe the bug**

When run multiple times on the same data set, dEploid oscillates between two different answers.  For example, 

first answer:
```
         Effective_K: 1.00005
          Inferred_K: 1
Adjusted_effective_K: 1.00005

Proportions:
1.09651e-05	  0.999976	1.32491e-05	2.21877e-08
```

second answer:
```
         Effective_K: 1.75907
          Inferred_K: 2
Adjusted_effective_K: 1.75907

Proportions:
  0.314951	4.04259e-06	  0.685045	3.59593e-08
```

In this specific, case its clear from looking at the data that K=1 is right.

dEploid version: 659c770cb7ed

**To Reproduce**
1. dEploid -vcf ERR2678989.vcf -plaf plaf.txt -o ERR2678989-nopanel -noPanel
2. -seed=0 produces one answer, but -seed=1 produces a different answer

I also tried increasing the run time from 800 to 8000 generations, but it didn't help.

**Expected behavior**
It seems that that the MCMC would be give the same answer each time.  However, it seems that there are two modes, and the MCMC cannot move between them.

**Additional context**
I might be able to help you improve the mixing.
